# base url
baseurl: /hamrobooks # Github repo name

#page title
page_title: "Hamro Books" # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

keywords: nepal school books, grade 10 books nepal, nepal grade 9 books, see books nepal

# App Info
# ios_app_id: 1234793120 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

# appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: "https://play.google.com/store/apps/details?id=io.github.ictsolved.hamrobooks" # Enter Google Play Store URL.
# presskit_download_link:
# https://emilbaehr.com # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
# Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/appicon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Hamro Books # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
# app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Grade 1 to Grade 10 books of Nepal in single application. You can save the books offline and read anywhere.
featured_image: assets/hamrobooks.png
enable_smart_app_banner: false # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
# your_name: ICT Solved!
your_link: https://ictsolved.github.io
# your_city: Kathmandu
email_address: ictsimplified@gmail.com
# facebook_username: saradgajurel
# instagram_username: ebaehr
# twitter_username: saradgajurel
# github_username: ictsolved
youtube_username: ictsolved

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Lite and Fast
    description: The app is small in size and very fast.
    fontawesome_icon_name: magic

  - title: Grade 1 to Grade 10 Books
    description: You can find school books from Grade 1 to Grade 10 in our application.
    fontawesome_icon_name: sync

  - title: English and Nepali Version of Books
    description: We have covered English as well as Nepali version of books in our application. You can read any version you like.
    fontawesome_icon_name: mobile

  - title: Offline Downloads
    description: You can download book once and access anywhere, anytime.
    fontawesome_icon_name: arrow-alt-circle-down

  - title: Dark Mode
    description: We have also included dark mode in our application to help you read the books without straining your eyes in night too.
    fontawesome_icon_name: adjust

  - title: Multi-lingual
    description: Our app includes Nepali and English language. You can use your preferred language on-the-go.
    fontawesome_icon_name: language

  - title: Modern UI
    description: Our application is built with the modern design trend and has an intuitive UI.
    fontawesome_icon_name: star

# Theme Settings
topbar_color: "#00A2C7"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
